# Generated by Django 4.2 on 2023-12-04 05:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0003_post_liked_alter_messages_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=True, null=True, related_name='LikedUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
