# Generated by Django 5.1 on 2024-08-12 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_post_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_image',
            new_name='is_file',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_image',
            new_name='post_file',
        ),
    ]
